version: '3'
services:
    php-apache:
        build: .
        ports:
            - 80:80
        volumes:
            - $PWD:/var/www/html:z
        links:
            - mariadb:mariadb

    mariadb:
        image: mariadb:10.1
        volumes:
            - $PWD/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: senha
            MYSQL_USER: user
            MYSQL_PASSWORD: senha
    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080        

volumes:
    mariadb: